blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://custats.info
    about: Visit the CUStats website for more information
  - name: Privacy Policy
    url: https://custats.info/privacy
    about: Read our privacy policy
